### ISSUE TITLE
国际服咖啡厅卡住 会卡图片检索

### ISSUE THREAD

**Issue by anlo1220** [baas-pro/baas#100]
国际服咖啡厅卡住
会卡图片检索
![image](https://github.com/baas-pro/baas/assets/61088753/6dac420d-6f3d-4331-a131-9795027d607c)

![image](https://github.com/baas-pro/baas/assets/61088753/0876f026-0db4-4b17-b1fd-f22439078250)

> 开始执行【咖啡厅】
═════════════════════════════════════════════════════════════════════════════════════════════════
v4.2.0.2  WARNING  07-10 11:27:40 │ 开始回到首页
v4.2.0.2  INFO     07-10 11:27:40 │ click (1233,11)
v4.2.0.2  INFO     07-10 11:27:44 │ 开始第 1/1 次图片检索 end:('home_setting', 'home_student')
v4.2.0.2  INFO     07-10 11:27:44 │ CI:home_setting S:1.00 I:1 R:True
v4.2.0.2  INFO     07-10 11:27:44 │ click (1233,11)
v4.2.0.2  INFO     07-10 11:27:44 │ double_click (851,262)
v4.2.0.2  INFO     07-10 11:27:45 │ click (923,186)
v4.2.0.2  INFO     07-10 11:27:49 │ 开始第 1/1 次图片检索 end:cafe_menu
v4.2.0.2  INFO     07-10 11:27:50 │ CI:cafe_menu S:-0.02 I:1 R:False
v4.2.0.2  INFO     07-10 11:27:50 │ CI:restart_news S:0.18 I:1 R:False
v4.2.0.2  INFO     07-10 11:27:50 │ CI:home_news S:0.06 I:1 R:False
v4.2.0.2  INFO     07-10 11:27:50 │ CI:home_news-intl S:0.07 I:1 R:False
v4.2.0.2  INFO     07-10 11:27:50 │ CI:home_store-error S:0.03 I:1 R:False
v4.2.0.2  INFO     07-10 11:27:50 │ CI:home_student S:1.00 I:1 R:True
v4.2.0.2  INFO     07-10 11:27:50 │ click (89,653)
v4.2.0.2  INFO     07-10 11:27:54 │ Now Loading 0 seconds...
v4.2.0.2  INFO     07-10 11:27:54 │ Now Loading 0 seconds...
v4.2.0.2  INFO     07-10 11:27:54 │ click (923,186)
v4.2.0.2  INFO     07-10 11:27:58 │ 开始第 2/1 次图片检索 end:cafe_menu
v4.2.0.2  INFO     07-10 11:27:58 │ CI:cafe_menu S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:27:58 │ CI:restart_news S:0.26 I:1 R:False
v4.2.0.2  INFO     07-10 11:27:58 │ CI:home_news S:-0.09 I:1 R:False
v4.2.0.2  INFO     07-10 11:27:58 │ CI:home_news-intl S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:27:58 │ CI:home_store-error S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:27:58 │ CI:home_student S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:27:58 │ CI:cafe_students-arrived S:-0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:27:58 │ CI:cafe_inc-fav S:0.27 I:1 R:False
v4.2.0.2  INFO     07-10 11:27:59 │ click (923,186)
v4.2.0.2  INFO     07-10 11:28:03 │ 开始第 3/2 次图片检索 end:cafe_menu
v4.2.0.2  INFO     07-10 11:28:03 │ CI:cafe_menu S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:03 │ CI:restart_news S:0.26 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:03 │ CI:home_news S:-0.09 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:03 │ CI:home_news-intl S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:03 │ CI:home_store-error S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:03 │ CI:home_student S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:03 │ CI:cafe_students-arrived S:-0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:03 │ CI:cafe_inc-fav S:0.27 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:03 │ click (923,186)
v4.2.0.2  INFO     07-10 11:28:07 │ 开始第 4/3 次图片检索 end:cafe_menu
v4.2.0.2  INFO     07-10 11:28:08 │ CI:cafe_menu S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:08 │ CI:restart_news S:0.26 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:08 │ CI:home_news S:-0.09 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:08 │ CI:home_news-intl S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:08 │ CI:home_store-error S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:08 │ CI:home_student S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:08 │ CI:cafe_students-arrived S:-0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:08 │ CI:cafe_inc-fav S:0.27 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:08 │ click (923,186)
v4.2.0.2  INFO     07-10 11:28:12 │ 开始第 5/4 次图片检索 end:cafe_menu
v4.2.0.2  INFO     07-10 11:28:12 │ CI:cafe_menu S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:12 │ CI:restart_news S:0.26 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:12 │ CI:home_news S:-0.09 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:12 │ CI:home_news-intl S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:12 │ CI:home_store-error S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:12 │ CI:home_student S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:12 │ CI:cafe_students-arrived S:-0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:12 │ CI:cafe_inc-fav S:0.27 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:13 │ Now Loading 0 seconds...
v4.2.0.2  INFO     07-10 11:28:13 │ click (923,186)
v4.2.0.2  INFO     07-10 11:28:17 │ 开始第 6/5 次图片检索 end:cafe_menu
v4.2.0.2  INFO     07-10 11:28:17 │ CI:cafe_menu S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:17 │ CI:restart_news S:0.26 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:17 │ CI:home_news S:-0.09 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:17 │ CI:home_news-intl S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:17 │ CI:home_store-error S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:17 │ CI:home_student S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:17 │ CI:cafe_students-arrived S:-0.03 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:17 │ CI:cafe_inc-fav S:0.26 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:18 │ click (923,186)
v4.2.0.2  INFO     07-10 11:28:22 │ 开始第 7/6 次图片检索 end:cafe_menu
v4.2.0.2  INFO     07-10 11:28:22 │ CI:cafe_menu S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:22 │ CI:restart_news S:0.26 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:22 │ CI:home_news S:-0.09 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:22 │ CI:home_news-intl S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:22 │ CI:home_store-error S:-0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:22 │ CI:home_student S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:22 │ CI:cafe_students-arrived S:0.00 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:22 │ CI:cafe_inc-fav S:0.27 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:22 │ click (923,186)
v4.2.0.2  INFO     07-10 11:28:26 │ 开始第 8/7 次图片检索 end:cafe_menu
v4.2.0.2  INFO     07-10 11:28:27 │ CI:cafe_menu S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:27 │ CI:restart_news S:0.26 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:27 │ CI:home_news S:-0.09 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:27 │ CI:home_news-intl S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:27 │ CI:home_store-error S:-0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:27 │ CI:home_student S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:27 │ CI:cafe_students-arrived S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:27 │ CI:cafe_inc-fav S:0.27 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:27 │ click (923,186)
v4.2.0.2  INFO     07-10 11:28:31 │ 开始第 9/8 次图片检索 end:cafe_menu
v4.2.0.2  INFO     07-10 11:28:31 │ CI:cafe_menu S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:31 │ CI:restart_news S:0.26 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:31 │ CI:home_news S:-0.09 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:31 │ CI:home_news-intl S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:31 │ CI:home_store-error S:-0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:31 │ CI:home_student S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:31 │ CI:cafe_students-arrived S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:31 │ CI:cafe_inc-fav S:0.27 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:32 │ click (923,186)
v4.2.0.2  INFO     07-10 11:28:36 │ 开始第 10/9 次图片检索 end:cafe_menu
v4.2.0.2  INFO     07-10 11:28:36 │ CI:cafe_menu S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:36 │ CI:restart_news S:0.26 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:36 │ CI:home_news S:-0.09 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:36 │ CI:home_news-intl S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:36 │ CI:home_store-error S:-0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:36 │ CI:home_student S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:36 │ CI:cafe_students-arrived S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:36 │ CI:cafe_inc-fav S:0.27 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:36 │ click (923,186)
v4.2.0.2  INFO     07-10 11:28:40 │ 开始第 11/10 次图片检索 end:cafe_menu
v4.2.0.2  WARNING  07-10 11:28:40 │ 卡识别了? MuMu模拟器:设置->其它->关闭后台保活 模拟器DPI:240 游戏图像分辨率:最高; 渲染模式:兼容; 后期处理:开; 抗锯齿:开; 国际服:繁中语言;
v4.2.0.2  INFO     07-10 11:28:41 │ CI:cafe_menu S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:41 │ CI:restart_news S:0.26 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:41 │ CI:home_news S:-0.09 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:41 │ CI:home_news-intl S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:41 │ CI:home_store-error S:-0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:41 │ CI:home_student S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:41 │ CI:cafe_students-arrived S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:41 │ CI:cafe_inc-fav S:0.27 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:41 │ click (923,186)
v4.2.0.2  INFO     07-10 11:28:45 │ 开始第 12/11 次图片检索 end:cafe_menu
v4.2.0.2  INFO     07-10 11:28:45 │ CI:cafe_menu S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:45 │ CI:restart_news S:0.26 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:46 │ CI:home_news S:-0.09 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:46 │ CI:home_news-intl S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:46 │ CI:home_store-error S:-0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:46 │ CI:home_student S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:46 │ CI:cafe_students-arrived S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:46 │ CI:cafe_inc-fav S:0.27 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:46 │ click (923,186)
v4.2.0.2  INFO     07-10 11:28:50 │ 开始第 13/12 次图片检索 end:cafe_menu
v4.2.0.2  INFO     07-10 11:28:50 │ CI:cafe_menu S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:50 │ CI:restart_news S:0.26 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:50 │ CI:home_news S:-0.09 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:50 │ CI:home_news-intl S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:50 │ CI:home_store-error S:-0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:50 │ CI:home_student S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:50 │ CI:cafe_students-arrived S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:50 │ CI:cafe_inc-fav S:0.27 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:50 │ click (923,186)
v4.2.0.2  INFO     07-10 11:28:54 │ 开始第 14/13 次图片检索 end:cafe_menu
v4.2.0.2  INFO     07-10 11:28:55 │ CI:cafe_menu S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:55 │ CI:restart_news S:0.26 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:55 │ CI:home_news S:-0.09 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:55 │ CI:home_news-intl S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:55 │ CI:home_store-error S:-0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:55 │ CI:home_student S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:55 │ CI:cafe_students-arrived S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:55 │ CI:cafe_inc-fav S:0.27 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:55 │ click (923,186)
v4.2.0.2  INFO     07-10 11:28:59 │ 开始第 15/14 次图片检索 end:cafe_menu
v4.2.0.2  INFO     07-10 11:28:59 │ CI:cafe_menu S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:59 │ CI:restart_news S:0.26 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:59 │ CI:home_news S:-0.09 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:59 │ CI:home_news-intl S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:59 │ CI:home_store-error S:-0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:59 │ CI:home_student S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:59 │ CI:cafe_students-arrived S:0.00 I:1 R:False
v4.2.0.2  INFO     07-10 11:28:59 │ CI:cafe_inc-fav S:0.27 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:00 │ click (923,186)
v4.2.0.2  INFO     07-10 11:29:04 │ 开始第 16/15 次图片检索 end:cafe_menu
v4.2.0.2  INFO     07-10 11:29:04 │ CI:cafe_menu S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:04 │ CI:restart_news S:0.26 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:04 │ CI:home_news S:-0.09 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:04 │ CI:home_news-intl S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:04 │ CI:home_store-error S:-0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:04 │ CI:home_student S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:04 │ CI:cafe_students-arrived S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:04 │ CI:cafe_inc-fav S:0.27 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:04 │ click (923,186)
v4.2.0.2  INFO     07-10 11:29:08 │ 开始第 17/16 次图片检索 end:cafe_menu
v4.2.0.2  INFO     07-10 11:29:09 │ CI:cafe_menu S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:09 │ CI:restart_news S:0.26 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:09 │ CI:home_news S:-0.09 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:09 │ CI:home_news-intl S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:09 │ CI:home_store-error S:-0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:09 │ CI:home_student S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:09 │ CI:cafe_students-arrived S:0.00 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:09 │ CI:cafe_inc-fav S:0.27 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:09 │ click (923,186)
v4.2.0.2  INFO     07-10 11:29:13 │ 开始第 18/17 次图片检索 end:cafe_menu
v4.2.0.2  INFO     07-10 11:29:13 │ CI:cafe_menu S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:13 │ CI:restart_news S:0.26 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:13 │ CI:home_news S:-0.09 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:13 │ CI:home_news-intl S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:13 │ CI:home_store-error S:-0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:13 │ CI:home_student S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:13 │ CI:cafe_students-arrived S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:13 │ CI:cafe_inc-fav S:0.27 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:14 │ click (923,186)
v4.2.0.2  INFO     07-10 11:29:17 │ 开始第 19/18 次图片检索 end:cafe_menu
v4.2.0.2  INFO     07-10 11:29:18 │ CI:cafe_menu S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:18 │ CI:restart_news S:0.26 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:18 │ CI:home_news S:-0.09 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:18 │ CI:home_news-intl S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:18 │ CI:home_store-error S:-0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:18 │ CI:home_student S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:18 │ CI:cafe_students-arrived S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:18 │ CI:cafe_inc-fav S:0.27 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:18 │ click (923,186)
v4.2.0.2  INFO     07-10 11:29:22 │ 开始第 20/19 次图片检索 end:cafe_menu
v4.2.0.2  INFO     07-10 11:29:23 │ CI:cafe_menu S:0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:23 │ CI:restart_news S:0.26 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:23 │ CI:home_news S:-0.09 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:23 │ CI:home_news-intl S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:23 │ CI:home_store-error S:-0.01 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:23 │ CI:home_student S:0.04 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:23 │ CI:cafe_students-arrived S:0.00 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:23 │ CI:cafe_inc-fav S:0.27 I:1 R:False
v4.2.0.2  INFO     07-10 11:29:23 │ click (923,186)

**Comment by KilluaaaCHEN** [comment]
已修复
