### ISSUE TITLE
[国际服] 添加对“網路存取不順暢。點選確認按鈕時將返回主畫面。”的应对措施

### ISSUE THREAD

**Issue by SALTWOOD** [baas-pro/baas#12]
如题。
![Screenshot_20231222_230503_Blue Archive](https://github.com/baas-pro/baas/assets/105980161/637b1933-e3aa-4bf2-98a1-b474011d913d)

还有另一种是“伺服器請求處理失敗。點選確認按鈕將返回主畫面。”

似乎是要一个很奇怪的触发条件，那个就只有一个确认按钮

**Comment by SALTWOOD** [comment]
不知道做没做，你叫我开我就开了（）

**Comment by KilluaaaCHEN** [comment]
fixed
