### ISSUE TITLE
下载但是打不开

### ISSUE THREAD

**Issue by LeoxfZhou** [baas-pro/baas#13]
![Screenshot 2023-12-22 110412](https://github.com/baas-pro/baas/assets/105604401/5e38f605-1fcc-4080-a14c-ac1080e841f1)
大佬是不是我电脑设置问题啊，我试了用win rar和7 zip解压但是打开都是这样，文件打开都是txt不能运行

**Comment by KilluaaaCHEN** [comment]
哪里下载的啊，你这是下载的源码，到qq群下载安装启动器

**Comment by LeoxfZhou** [comment]
> 哪里下载的啊，你这是下载的源码，到qq群下载安装启动器
好得，谢谢大佬
