### ISSUE TITLE
特殊悬赏、通缉关卡6会卡住，咖啡厅招待券最后一步确认会有点不了的情况

### ISSUE THREAD

**Issue by zhouzh52** [baas-pro/baas#17]
![1703388934802](https://github.com/baas-pro/baas/assets/110249057/421a68e9-5d1f-4911-9168-a99e639f2fbf)
![image](https://github.com/baas-pro/baas/assets/110249057/de8e7cd5-2e6a-4fa5-b0d4-1fa5b4d3ef1e)

**Comment by zhouzh52** [comment]
咖啡厅招待券卡确认识别结果
![image](https://github.com/baas-pro/baas/assets/110249057/103cfb0a-9dff-4706-8e6e-f5a0a171447f)
特殊拦截识别结果
![image](https://github.com/baas-pro/baas/assets/110249057/3f1afa57-077f-47e0-a322-383697392ad8)

**Comment by zhouzh52** [comment]
![image](https://github.com/baas-pro/baas/assets/110249057/d709f200-1225-4933-9558-c49b2c8a4597)
![image](https://github.com/baas-pro/baas/assets/110249057/bfffedd6-48e3-4b8e-98cf-8489f807d6c6)

**Comment by KilluaaaCHEN** [comment]
已修复 请更新至v2.1.0
