### ISSUE TITLE
OCR初始化失败

### ISSUE THREAD

**Issue by SophiaLeight** [baas-pro/baas#2]
═════════════════════════════════════════════════════════════════════════════════════════════════
开始初始化OCR
═════════════════════════════════════════════════════════════════════════════════════════════════
v2.0.1  CRITICAL 12-21 21:36:46 │ 解决方法1: 删除 C:\Users\你的用户名\AppData\Roaming\cnocr\2.2 目录 重新运行脚本会重新下载(可能要用梯子上网)
v2.0.1  CRITICAL 12-21 21:36:46 │ 解决方法2: 到QQ群下载2.2.7z压缩包,解压到 C:\Users\你的用户名\AppData\Roaming\cnocr\2.2 目录里面
v2.0.1  CRITICAL 12-21 21:36:46 │ OCR初始化失败:Failed to download model: ch_PP-OCRv3_det_infer-onnx.zip.
	Please open your VPN and try again. 
	If this error persists, please follow the instruction at [CnSTD/CnOCR Doc](https://www.breezedeus.com/cnocr) to manually download the model files.

**Comment by irpachen** [comment]
相同问题，贴一个我初始化OCR之前报的error
═════════════════════════════════════════════════════════════════════════════════════════════════
开始连接模拟器:127.0.0.1:16384
═════════════════════════════════════════════════════════════════════════════════════════════════
v2.0.2  ERROR    12-21 22:14:57 │ [36m[D 231221 22:14:57 __init__:661][39m [pid:37008] [127.0.0.1:16384] kill process(ps): uiautomator
v2.0.2  ERROR    12-21 22:14:57 │ [36m[D 231221 22:14:57 __init__:391][39m [pid:37008] [127.0.0.1:16384] Install app-uiautomator.apk
v2.0.2  ERROR    12-21 22:14:58 │ [36m[D 231221 22:14:58 __init__:391][39m [pid:37008] [127.0.0.1:16384] Install app-uiautomator-test.apk
v2.0.2  ERROR    12-21 22:14:59 │ [36m[D 231221 22:14:59 __init__:682][39m [pid:37008] [127.0.0.1:16384] uiautomator-v2 is starting ... left: 40.0s
v2.0.2  ERROR    12-21 22:15:00 │ [36m[D 231221 22:15:00 __init__:682][39m [pid:37008] [127.0.0.1:16384] uiautomator-v2 is starting ... left: 39.0s
v2.0.2  ERROR    12-21 22:15:00 │ [36m[D 231221 22:15:00 __init__:696][39m [pid:37008] [127.0.0.1:16384] show float window
v2.0.2  ERROR    12-21 22:15:01 │ [36m[D 231221 22:15:01 __init__:682][39m [pid:37008] [127.0.0.1:16384] uiautomator-v2 is starting ... left: 37.9s
v2.0.2  ERROR    12-21 22:15:01 │ [32m[I 231221 22:15:01 __init__:643][39m [pid:37008] [127.0.0.1:16384] uiautomator back to normal
v2.0.2  INFO     12-21 22:15:01 │ 模拟器连接成功:-08:85:fe:e5:80:00-2206122SC
v2.0.2  INFO     12-21 22:15:01 │ 
═════════════════════════════════════════════════════════════════════════════════════════════════
开始初始化OCR
然后是上述报错

**Comment by KilluaaaCHEN** [comment]
# 已修复 v2.0.3
