### ISSUE TITLE
12章和13章脚本无法自动点击“是否移动部队”和”是否结束回合“界面

### ISSUE THREAD

**Issue by lymiyaqwq** [baas-pro/baas#23]
**电脑系统信息**
Windows

**Baas版本**
v2.0.5

**模拟器信息**
雷电

**游戏区服**
国服B包

**问题描述**
与上一个12章的问题差不多 就是有弹窗就无法自动点确定 必须手动点击后才能继续

**Comment by KilluaaaCHEN** [comment]
已修复到v2.0.6
