### ISSUE TITLE
给image.py中的detect和compare_image函数增加超时

### ISSUE THREAD

**Issue by 0x504B0304** [baas-pro/baas#24]
我是用虚拟机挂脚本的，会经常用远程桌面连接，用远程桌面连接会经常改变显示器的分辨率，导致截图一直错位，无法恢复，然后识别失败，如果分辨率改变不在预期工况内，能否先对detect和compare_image函数增加超时，一旦识别超时则重启ba？如果是觉得调用的位置太多不好修改可以考虑在函数里直接抛个异常，最外面直接try-catch

**Comment by KilluaaaCHEN** [comment]
fixed
