### ISSUE TITLE
无法启动-Max retries exceeded with url

### ISSUE THREAD

**Issue by Elgalas** [baas-pro/baas#26]
**电脑系统信息**
- 系统类型：Windows

**Baas版本**
- Baas 版本号：v2.0.6

**模拟器信息**
- 模拟器类型：Mumu12
- 模拟器版本号：V3.7.0（2484）

**游戏区服**
- 游戏区服：国际服

**问题描述**
- 功能模块：无法启动
- 详细问题描述：无法启动，按提示下载文件放入指定文件夹仍然报同样的错误

**运行截图/动图或视频**
- 如果可能，请附加运行时的截图、GIF 或视频以帮助说明您遇到的问题
![image](https://github.com/baas-pro/baas/assets/17876505/4119fb3e-ca41-4888-956a-8182623676b5)

**运行日志**
- 请附上位于 `runtime/logs` 目录下的运行日志文件，以便我们分析问题。
[2023-12-28_baas.zip](https://github.com/baas-pro/baas/files/13782908/2023-12-28_baas.zip)

**联系方式**
- QQ号: 1348507703

**其他补充信息**
- 在这里添加任何其他上下文信息。

**Comment by KilluaaaCHEN** [comment]
从群里重新下载最新的文件复制过去，即可解决
