### ISSUE TITLE
扫荡困难关卡卡住了

### ISSUE THREAD

**Issue by Arischid** [baas-pro/baas#27]
**电脑系统信息**
- 系统类型：Windows11
- 苹果电脑芯片型号：[例如 Intel, M1, M2]

**Baas版本**
- Baas 版本号：v2.0.6

**模拟器信息**
- 模拟器类型：雷电
- 模拟器版本号：9

**游戏区服**
- 游戏区服：国服官包

**问题描述**
- 功能模块：困难扫荡
- 详细问题描述：卡在困难选择关卡的界面不动了，不知道是不是因为我图没开完的原因，但我前几天用的时候没开完图也行

**运行截图/动图或视频**

![image](https://github.com/baas-pro/baas/assets/38714580/a0b23e19-4206-40dd-ac9c-b9acf5ab530b)
![image](https://github.com/baas-pro/baas/assets/38714580/a256c5aa-cf10-4914-93a6-f8b518d20e01)

**运行日志**
- 请附上位于 `runtime/logs` 目录下的运行日志文件，以便我们分析问题。

-v2.0.6  INFO     12-29 00:27:14 │ 
═════════════════════════════════════════════════════════════════════════════════════════════════
开始执行【扫荡困难关卡】
═════════════════════════════════════════════════════════════════════════════════════════════════
v2.0.6  WARNING  12-29 00:27:14 │ 开始回到首页
v2.0.6  INFO     12-29 00:27:14 │ click (1233,11)
v2.0.6  INFO     12-29 00:27:15 │ 开始第 1 次图片检索 end:home_student
v2.0.6  INFO     12-29 00:27:15 │ compare_image home_student SSIM:0.99 Result:True
v2.0.6  INFO     12-29 00:27:15 │ click (1233,11)
v2.0.6  INFO     12-29 00:27:15 │ double_click (851,262)
v2.0.6  INFO     12-29 00:27:16 │ 开始第 1 次图片检索 end:normal_task_choose-region
v2.0.6  INFO     12-29 00:27:16 │ compare_image normal_task_choose-region SSIM:-0.05 Result:False
v2.0.6  INFO     12-29 00:27:16 │ compare_image home_news SSIM:0.02 Result:False
v2.0.6  INFO     12-29 00:27:16 │ compare_image home_news-intl SSIM:0.07 Result:False
v2.0.6  INFO     12-29 00:27:16 │ compare_image home_store-error SSIM:0.03 Result:False
v2.0.6  INFO     12-29 00:27:16 │ compare_image home_student SSIM:0.99 Result:True
v2.0.6  INFO     12-29 00:27:16 │ click (1200,573)
v2.0.6  INFO     12-29 00:27:16 │ 开始第 2 次图片检索 end:normal_task_choose-region
v2.0.6  INFO     12-29 00:27:17 │ compare_image normal_task_choose-region SSIM:-0.03 Result:False
v2.0.6  INFO     12-29 00:27:17 │ compare_image home_news SSIM:0.04 Result:False
v2.0.6  INFO     12-29 00:27:17 │ compare_image home_news-intl SSIM:0.11 Result:False
v2.0.6  INFO     12-29 00:27:17 │ compare_image home_store-error SSIM:0.03 Result:False
v2.0.6  INFO     12-29 00:27:17 │ compare_image home_student SSIM:0.69 Result:False
v2.0.6  INFO     12-29 00:27:17 │ compare_image normal_task_menu SSIM:-0.01 Result:False
v2.0.6  INFO     12-29 00:27:17 │ 开始第 3 次图片检索 end:normal_task_choose-region
v2.0.6  INFO     12-29 00:27:17 │ compare_image normal_task_choose-region SSIM:-0.03 Result:False
v2.0.6  INFO     12-29 00:27:17 │ compare_image home_news SSIM:0.06 Result:False
v2.0.6  INFO     12-29 00:27:17 │ compare_image home_news-intl SSIM:0.11 Result:False
v2.0.6  INFO     12-29 00:27:17 │ compare_image home_store-error SSIM:0.03 Result:False
v2.0.6  INFO     12-29 00:27:17 │ compare_image home_student SSIM:0.57 Result:False
v2.0.6  INFO     12-29 00:27:17 │ compare_image normal_task_menu SSIM:-0.01 Result:False
v2.0.6  INFO     12-29 00:27:17 │ 开始第 4 次图片检索 end:normal_task_choose-region
v2.0.6  INFO     12-29 00:27:17 │ compare_image normal_task_choose-region SSIM:0.01 Result:False
v2.0.6  INFO     12-29 00:27:17 │ compare_image home_news SSIM:0.05 Result:False
v2.0.6  INFO     12-29 00:27:17 │ compare_image home_news-intl SSIM:0.10 Result:False
v2.0.6  INFO     12-29 00:27:17 │ compare_image home_store-error SSIM:0.03 Result:False
v2.0.6  INFO     12-29 00:27:17 │ compare_image home_student SSIM:0.02 Result:False
v2.0.6  INFO     12-29 00:27:17 │ compare_image normal_task_menu SSIM:0.01 Result:False
v2.0.6  INFO     12-29 00:27:17 │ 开始第 5 次图片检索 end:normal_task_choose-region
v2.0.6  INFO     12-29 00:27:17 │ compare_image normal_task_choose-region SSIM:0.01 Result:False
v2.0.6  INFO     12-29 00:27:17 │ compare_image home_news SSIM:0.05 Result:False
v2.0.6  INFO     12-29 00:27:17 │ compare_image home_news-intl SSIM:0.10 Result:False
v2.0.6  INFO     12-29 00:27:17 │ compare_image home_store-error SSIM:0.03 Result:False
v2.0.6  INFO     12-29 00:27:17 │ compare_image home_student SSIM:0.02 Result:False
v2.0.6  INFO     12-29 00:27:17 │ compare_image normal_task_menu SSIM:0.01 Result:False
v2.0.6  INFO     12-29 00:27:18 │ 开始第 6 次图片检索 end:normal_task_choose-region
v2.0.6  INFO     12-29 00:27:18 │ compare_image normal_task_choose-region SSIM:0.01 Result:False
v2.0.6  INFO     12-29 00:27:18 │ compare_image home_news SSIM:0.05 Result:False
v2.0.6  INFO     12-29 00:27:18 │ compare_image home_news-intl SSIM:0.10 Result:False
v2.0.6  INFO     12-29 00:27:18 │ compare_image home_store-error SSIM:0.03 Result:False
v2.0.6  INFO     12-29 00:27:18 │ compare_image home_student SSIM:0.02 Result:False
v2.0.6  INFO     12-29 00:27:18 │ compare_image normal_task_menu SSIM:0.01 Result:False
v2.0.6  INFO     12-29 00:27:18 │ 开始第 7 次图片检索 end:normal_task_choose-region
v2.0.6  INFO     12-29 00:27:18 │ compare_image normal_task_choose-region SSIM:0.01 Result:False
v2.0.6  INFO     12-29 00:27:18 │ compare_image home_news SSIM:0.05 Result:False
v2.0.6  INFO     12-29 00:27:18 │ compare_image home_news-intl SSIM:0.10 Result:False
v2.0.6  INFO     12-29 00:27:18 │ compare_image home_store-error SSIM:0.03 Result:False
v2.0.6  INFO     12-29 00:27:18 │ compare_image home_student SSIM:0.02 Result:False
v2.0.6  INFO     12-29 00:27:18 │ compare_image normal_task_menu SSIM:0.01 Result:False
v2.0.6  INFO     12-29 00:27:18 │ 开始第 8 次图片检索 end:normal_task_choose-region
v2.0.6  INFO     12-29 00:27:18 │ compare_image normal_task_choose-region SSIM:0.01 Result:False
v2.0.6  INFO     12-29 00:27:18 │ compare_image home_news SSIM:0.05 Result:False
v2.0.6  INFO     12-29 00:27:18 │ compare_image home_news-intl SSIM:0.10 Result:False
v2.0.6  INFO     12-29 00:27:18 │ compare_image home_store-error SSIM:0.03 Result:False
v2.0.6  INFO     12-29 00:27:18 │ compare_image home_student SSIM:0.02 Result:False
v2.0.6  INFO     12-29 00:27:18 │ compare_image normal_task_menu SSIM:0.01 Result:False
v2.0.6  INFO     12-29 00:27:18 │ 开始第 9 次图片检索 end:normal_task_choose-region
v2.0.6  INFO     12-29 00:27:18 │ compare_image normal_task_choose-region SSIM:0.01 Result:False
v2.0.6  INFO     12-29 00:27:18 │ compare_image home_news SSIM:0.05 Result:False
v2.0.6  INFO     12-29 00:27:18 │ compare_image home_news-intl SSIM:0.10 Result:False
v2.0.6  INFO     12-29 00:27:18 │ compare_image home_store-error SSIM:0.03 Result:False
v2.0.6  INFO     12-29 00:27:18 │ compare_image home_student SSIM:0.02 Result:False
v2.0.6  INFO     12-29 00:27:18 │ compare_image normal_task_menu SSIM:0.01 Result:False
v2.0.6  INFO     12-29 00:27:18 │ 开始第 10 次图片检索 end:normal_task_choose-region
v2.0.6  INFO     12-29 00:27:19 │ compare_image normal_task_choose-region SSIM:0.12 Result:False
v2.0.6  INFO     12-29 00:27:19 │ compare_image home_news SSIM:0.05 Result:False
v2.0.6  INFO     12-29 00:27:19 │ compare_image home_news-intl SSIM:-0.07 Result:False
v2.0.6  INFO     12-29 00:27:19 │ compare_image home_store-error SSIM:0.03 Result:False
v2.0.6  INFO     12-29 00:27:19 │ compare_image home_student SSIM:0.02 Result:False
v2.0.6  INFO     12-29 00:27:19 │ compare_image normal_task_menu SSIM:-0.02 Result:False
v2.0.6  INFO     12-29 00:27:19 │ 开始第 11 次图片检索 end:normal_task_choose-region
v2.0.6  INFO     12-29 00:27:19 │ compare_image normal_task_choose-region SSIM:0.09 Result:False
v2.0.6  INFO     12-29 00:27:19 │ compare_image home_news SSIM:0.05 Result:False
v2.0.6  INFO     12-29 00:27:19 │ compare_image home_news-intl SSIM:-0.01 Result:False
v2.0.6  INFO     12-29 00:27:19 │ compare_image home_store-error SSIM:0.03 Result:False
v2.0.6  INFO     12-29 00:27:19 │ compare_image home_student SSIM:0.02 Result:False
v2.0.6  INFO     12-29 00:27:19 │ compare_image normal_task_menu SSIM:1.00 Result:True
v2.0.6  INFO     12-29 00:27:19 │ click (816,263)
v2.0.6  INFO     12-29 00:27:20 │ 开始第 12 次图片检索 end:normal_task_choose-region
v2.0.6  INFO     12-29 00:27:20 │ compare_image normal_task_choose-region SSIM:0.09 Result:False
v2.0.6  INFO     12-29 00:27:20 │ compare_image home_news SSIM:0.05 Result:False
v2.0.6  INFO     12-29 00:27:20 │ compare_image home_news-intl SSIM:-0.01 Result:False
v2.0.6  INFO     12-29 00:27:20 │ compare_image home_store-error SSIM:0.03 Result:False
v2.0.6  INFO     12-29 00:27:20 │ compare_image home_student SSIM:0.02 Result:False
v2.0.6  INFO     12-29 00:27:20 │ compare_image normal_task_menu SSIM:0.99 Result:True
v2.0.6  INFO     12-29 00:27:20 │ click (816,263)
v2.0.6  INFO     12-29 00:27:21 │ 开始第 13 次图片检索 end:normal_task_choose-region
v2.0.6  INFO     12-29 00:27:21 │ compare_image normal_task_choose-region SSIM:-0.00 Result:False
v2.0.6  INFO     12-29 00:27:21 │ compare_image home_news SSIM:0.06 Result:False
v2.0.6  INFO     12-29 00:27:21 │ compare_image home_news-intl SSIM:0.11 Result:False
v2.0.6  INFO     12-29 00:27:21 │ compare_image home_store-error SSIM:0.03 Result:False
v2.0.6  INFO     12-29 00:27:21 │ compare_image home_student SSIM:0.07 Result:False
v2.0.6  INFO     12-29 00:27:21 │ compare_image normal_task_menu SSIM:-0.00 Result:False
v2.0.6  INFO     12-29 00:27:21 │ 开始第 14 次图片检索 end:normal_task_choose-region
v2.0.6  INFO     12-29 00:27:21 │ compare_image normal_task_choose-region SSIM:1.00 Result:True
v2.0.6  INFO     12-29 00:27:21 │ check_rgb area:(1000, 150) target_rgb:(198, 66, 66) get_rgb:(245, 248, 248) color_dist:261.64 result:False
v2.0.6  INFO     12-29 00:27:21 │ click (1062,154)
v2.0.6  INFO     12-29 00:27:22 │ check_rgb area:(1000, 150) target_rgb:(198, 66, 66) get_rgb:(202, 86, 102) color_dist:41.38 result:True
v2.0.6  CRITICAL 12-29 00:27:22 │ Exception occurred: list index out of range
v2.0.6  CRITICAL 12-29 00:27:22 │ Stack trace:
Traceback (most recent call last):
  File "common\process.py", line 12, in baas_dashboard
  File "common\baas.py", line 188, in dashboard
  File "modules\scan\hard_task.py", line 9, in start
  File "modules\scan\normal_task.py", line 35, in start
  File "modules\scan\normal_task.py", line 55, in start_scan
  File "common\stage.py", line 144, in stage_convert
  File "common\stage.py", line 144, in 
  File "common\stage.py", line 135, in convert_string
IndexError: list index out of range

**Comment by KilluaaaCHEN** [comment]
第一个配置写错了,应该是1-1-3 你写成了1-1 3

**Comment by csj001** [comment]
我也有这个问题...
