### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by UVJkiNTQ** [baas-pro/baas#28]
**电脑系统信息**
- 系统类型：Windows 

**Baas版本**
- Baas 版本号：最新
根据git打印信息：
https://gitee.com/baas-pro/baas-win/commit/e2d4e0191c3c5bf89d1a22995b1bafd97060dbea

今日启动更新后出现报错。
参照gitee版本号，有问题的版本：[v2.1.0.2](https://gitee.com/baas-pro/baas-win/tree/v2.1.0.2)
退回旧版后正常启动，回退的版本：[v2.0.6.1](https://gitee.com/baas-pro/baas-win/tree/v2.0.6.1)

**Comment by UVJkiNTQ** [comment]
`torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
2024-01-01 23:30:35.0324735 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1983 onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.
torch\_jit_internal.py:857: UserWarning: Unable to retrieve source for @torch.jit._overload function: <function _DenseLayer.forward at 0x00000172963B2820>.
  warnings.warn(
torch\_jit_internal.py:857: UserWarning: Unable to retrieve source for @torch.jit._overload function: <function _DenseLayer.forward at 0x00000172963D11F0>.
  warnings.warn(
torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
2024-01-01 23:30:40.6839735 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1983 onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.
torch\_jit_internal.py:857: UserWarning: Unable to retrieve source for @torch.jit._overload function: <function _DenseLayer.forward at 0x000001DC4A5E2820>.
  warnings.warn(
torch\_jit_internal.py:857: UserWarning: Unable to retrieve source for @torch.jit._overload function: <function _DenseLayer.forward at 0x000001DC4A6011F0>.
  warnings.warn(
必须从启动器Baas_Windows启动Baas脚本
如果你是第一次遇到这个错误，请从QQ群重新下载最新启动器覆盖原来的启动器。
不需要重新下载和安装`

**Comment by KilluaaaCHEN** [comment]
必须从启动器Baas_Windows启动Baas脚本 
如果你是第一次遇到这个错误，请从QQ群重新下载最新启动器覆盖原来的启动器。 
不需要重新下载和安装

**Comment by UVJkiNTQ** [comment]
> 必须从启动器Baas_Windows启动Baas脚本 
> 如果你是第一次遇到这个错误，请从QQ群重新下载最新启动器覆盖原来的启动器。 
> 不需要重新下载和安装

看了下launcher的内容，这个错误应该是gitee上的可能存在错误的baas.exe引发的。

launcher中显示使用git pull更新。手动覆盖这个文件，可能会导致存在手动更改而导致git pull报错？

**Comment by UVJkiNTQ** [comment]
搞懂了，launcher.py不是正式的启动器，群文件的exe才是……
