### ISSUE TITLE
困难图11-2-task 最后一个action多了'ec':true

### ISSUE THREAD

**Issue by pur1fying** [baas-pro/baas#30]
**电脑系统信息**
- 系统类型：[Windows / macOS]
- 苹果电脑芯片型号：[例如 Intel, M1, M2]

**Baas版本**
- Baas 版本号：[例如 v2.0.5]

**模拟器信息**
- 模拟器类型：[例如 Mumu12, 雷电, 夜神 ...]
- 模拟器版本号：[例如 12]

**游戏区服**
- 游戏区服：[例如 国服官包 国服B包 日服 国际服]

**问题描述**
- 功能模块：[例如 普通开图 咖啡厅 日程 ...]
- 详细问题描述：[请尽可能详细描述遇到的问题]

**运行截图/动图或视频**
- 如果可能，请附加运行时的截图、GIF 或视频以帮助说明您遇到的问题

**运行日志**
- 请附上位于 `runtime/logs` 目录下的运行日志文件，以便我们分析问题。

**联系方式**
- QQ号: 

**其他补充信息**
- 在这里添加任何其他上下文信息。

**Comment by KilluaaaCHEN** [comment]
fixed
