### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by alanseal** [baas-pro/baas#31]
**电脑系统信息**
- 系统类型：Windows 

**Baas版本**
- Baas 版本号：v2.1.0

**问题描述**
- 详细问题描述：

更新失败 Command '['git', 'pull', 'origin', 'main']' returned non-zero exit status 128.

发生异常: Command '['git', 'log', '--pretty=format:%ad %d %s', '--date=short', '-n', '10']' returned non-zero exit status 128.
堆栈跟踪:
Traceback (most recent call last):
  File "launcher.py", line 155, in main
  File "launcher.py", line 27, in git_clone_and_pull
  File "launcher.py", line 95, in git_logs
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['git', 'log', '--pretty=format:%ad %d %s', '--date=short', '-n', '10']' returned non-zero exit status 128.

**运行截图/动图或视频**
- 如果可能，请附加运行时的截图、GIF 或视频以帮助说明您遇到的问题
![{331973D1-C209-4c9d-9533-341754758C97}](https://github.com/baas-pro/baas/assets/111694000/fc447743-e081-4389-8563-a96efa9c1049)

**Comment by KilluaaaCHEN** [comment]
打开命令行，输入，一次一条
```bash
cd D:
cd D:/AUTO RUN/baas
git config --global --add safe.directory 'D:/AUTO RUN/baas'
```

**Comment by alanseal** [comment]
已解决，感谢
问题本质上是我把baas装在exFAT格式的盘里了(‘-‘*)，导致出现截图中问题
把baas换到NTFS的盘里面就好了
