### ISSUE TITLE
有关于进行日程任务时候的的问题

### ISSUE THREAD

**Issue by 123xuanhua** [baas-pro/baas#32]
**电脑系统信息**i5 3050ti
**电脑系统信息**12500
- 系统类型：[Windows / macOS]   win
- 苹果电脑芯片型号：[例如 Intel, M1, M2]

**Baas版本**v2.1.0
- Baas 版本号：[例如 v2.0.5]

**模拟器信息**
- 模拟器类型：[例如 Mumu12, 雷电, 夜神 ...]  mumu
- 模拟器版本号：[例如 12]   12

**游戏区服**
- 游戏区服：[例如 国服官包 国服B包 日服 国际服]
 日服 
**问题描述**
- 功能模块：[例如 普通开图 咖啡厅 日程 ...]       日程
- 详细问题描述：[请尽可能详细描述遇到的问题]
在进行日程任务的时候，会一直点击小边框的右上角，导致卡住了，但是再重新开一次baas即可使用
**运行截图/动图或视频**
- 如果可能，请附加运行时的截图、GIF 或视频以帮助说明您遇到的问题

Uploading b14bae3798a194e47e361f205965b107.mp4…

**运行日志**
- 请附上位于 `runtime/logs` 目录下的运行日志文件，以便我们分析问题。

**联系方式**
- QQ号: 
2630172946
**其他补充信息**
- 在这里添加任何其他上下文信息。

**Comment by KilluaaaCHEN** [comment]
是每次必现呢,还是偶发的bug

**Comment by KilluaaaCHEN** [comment]
太久未反馈，暂时关闭，有问题再反馈，谢谢
