### ISSUE TITLE
普通开图与困难开图中关卡设置下区域的说明文本中没有17-20章的配队说明文本

### ISSUE THREAD

**Issue by ice-forever** [baas-pro/baas#34]
**电脑系统信息**
- 系统类型：Windows

**Baas版本**
- Baas 版本号：2024-01-05  (HEAD -> main, origin/main, origin/HEAD) 温泉活动任务关联;修复扫荡bug;三连弹窗

**模拟器信息**
- 模拟器类型：Mumu12
- 模拟器版本号：12

**游戏区服**
- 游戏区服：国服官包

**问题描述**
- 功能模块：普通开图与困难关卡开图
- 详细问题描述：17-20章开图所需的队伍配置未补充

**运行截图/动图或视频**
![image](https://github.com/baas-pro/baas/assets/74451255/d6ad7ae2-2a27-4411-84e9-051a788db4ee)

**Comment by KilluaaaCHEN** [comment]
因为开图是按照国服进度做的,暂时还没做16之后的开图数据,所以没有写

**Comment by ice-forever** [comment]
> 因为开图是按照国服进度做的,暂时还没做16之后的开图数据,所以没有写

哎，那要是开图数据没有写的话，右边下拉框里面的17-20是不是可以考虑先隐藏了。好有误导性
![image](https://github.com/baas-pro/baas/assets/74451255/3e788761-4136-4284-8d91-87c6ce3610d0)

**Comment by ice-forever** [comment]
还有购买体力的这个部分希望加些说明文本，这个购买次数是2次相当于两个体力都买一次然后刷新再买一次么
![image](https://github.com/baas-pro/baas/assets/74451255/b90119e5-2b8d-4ae7-95af-c71c47837153)

**Comment by KilluaaaCHEN** [comment]
好的,我优化一下文案
