### ISSUE TITLE
满体力进竞技场领取每日奖励无法识别体力溢出通知界面

### ISSUE THREAD

**Issue by zongzirua** [baas-pro/baas#35]
**电脑系统信息**
- 系统类型：Windows 

**Baas版本**
- Baas 版本号：2.1.1

**模拟器信息**
- 模拟器类型：雷电
- 模拟器版本号：9.0.26

**游戏区服**
- 游戏区服：日服 

**问题描述**
- 功能模块：竞技场
- 详细问题描述：满体力进竞技场领取每日奖励无法识别体力溢出通知界面，虽然扫荡关卡清体力可以解决，但是没有日服的活动，不想扫荡普通/困难关卡

**运行截图/动图或视频**
- 如果可能，请附加运行时的截图、GIF 或视频以帮助说明您遇到的问题
![image](https://github.com/baas-pro/baas/assets/145755457/272cb826-fe60-4cc4-a20e-7abe8ba71882)
**运行日志**
- 请附上位于 `runtime/logs` 目录下的运行日志文件，以便我们分析问题。
[2024-01-07_baas1.log](https://github.com/baas-pro/baas/files/13850551/2024-01-07_baas1.log)

**联系方式**
- QQ号: 1757503889

**其他补充信息**
- 在这里添加任何其他上下文信息。

**Comment by KilluaaaCHEN** [comment]
已修复至v2.2.0
