### ISSUE TITLE
学园交流会功能在缺少学园交流会票券时卡在识别阶段，没有下一步操作

### ISSUE THREAD

**Issue by Mumouren** [baas-pro/baas#37]
**电脑系统信息**
- 系统类型：Windows

**Baas版本**
- Baas 版本号：v2.1.1

**模拟器信息**
- 模拟器类型：Mumu12
- 模拟器版本号：12

**游戏区服**
- 游戏区服：国际服

**问题描述**
- 功能模块：学园交流会
- 详细问题描述：学园交流会在无票时会卡在识别阶段，并且没有下一步操作
**运行截图/动图或视频**
![A](https://github.com/baas-pro/baas/assets/73356797/bb64dedd-ca7f-4999-b8f4-abd1e6c70d0d)

**运行日志**
[学园交流会.txt](https://github.com/baas-pro/baas/files/13852546/default.txt)
（不支持HTML类文件？假如需要的话我我周五找时间再用网盘上传一下）

**联系方式**
- QQ号: 632247656（人在学校 工作日没法回复）

**其他补充信息**
无

**Comment by KilluaaaCHEN** [comment]
已修复至v2.2.0
