### ISSUE TITLE
制造选择分支时 点击分支与点击开始建造时间间隔太短 以至于无法正确制造 

### ISSUE THREAD

**Issue by landibex** [baas-pro/baas#38]
**电脑系统信息**  
- 系统类型：[Windows / macOS]
- 苹果电脑芯片型号：[例如 Intel, M1, M2]
windows 11
**Baas版本**
- Baas 版本号：[例如 v2.0.5]
最新版 具体多少不太清楚
**模拟器信息**
- 模拟器类型：[例如 Mumu12, 雷电, 夜神 ...]
- 模拟器版本号：[例如 12]
mumu
**游戏区服**
- 游戏区服：[例如 国服官包 国服B包 日服 国际服]
国服b包
**问题描述**
- 功能模块：[例如 普通开图 咖啡厅 日程 ...]
- 详细问题描述：[请尽可能详细描述遇到的问题]
如标题
**运行截图/动图或视频**
- 如果可能，请附加运行时的截图、GIF 或视频以帮助说明您遇到的问题

**运行日志**
- 请附上位于 `runtime/logs` 目录下的运行日志文件，以便我们分析问题。

**联系方式**
- QQ号: 2561003340

**其他补充信息**
- 在这里添加任何其他上下文信息。

**Comment by KilluaaaCHEN** [comment]
已修复至v2.2.0
