### ISSUE TITLE
不知是远程控制软件还是代理的关系，导致出现[WinError 10054]，无法启动baas

### ISSUE THREAD

**Issue by qwe853531778** [baas-pro/baas#41]
- 系统类型：Windows 10 22H2 19045.3803

- Baas 版本号： v2.1.1

- 模拟器类型： Mumu12
- 模拟器版本号：12

- 游戏区服：日服 

**问题描述**
- 功能模块：启动
- 详细问题描述：重启电脑可以正常运行，但使用代理或远程控制软件后，再重新打开模拟器，和baas尝试运行，会出现报错： [WinError 10054] 远程主机强迫关闭了一个现有的连接。使用的代理软件clash，nekoray。使用的远程控制软件 todesk，向日葵。

**运行日志**
v2.1.1.1  INFO     01-10 10:16:48 │
═════════════════════════════════════════════════════════════════════════════════════════════════

日志初始化成功
═════════════════════════════════════════════════════════════════════════════════════════════════
v2.1.1.1  INFO     01-10 10:16:48 │
═════════════════════════════════════════════════════════════════════════════════════════════════

开始连接模拟器:127.0.0.1:16384
═════════════════════════════════════════════════════════════════════════════════════════════════
v2.1.1.1  CRITICAL 01-10 10:16:48 │ 模拟器连接失败，必须打开模拟器! 然后设置对应模拟器端口 Baas->Baas设置->模拟器Serial

v2.1.1.1  CRITICAL 01-10 10:16:48 │ 如果模拟器多开，ADB端口会不一样。点击模拟器问题诊断->查看ADB调试端口

v2.1.1.1  CRITICAL 01-10 10:16:48 │ 如果报错HTTPSConnectionPool(host='github.com',port=443): Max retries exceeded with url...到QQ群下载《异常问题文件下载/atx-agent_0.10.0_linux_386》 复制到 C:\Users\你的用户名\.uiautomator2\cache\atx-agent_0.10.0_linux_386.tar.gz-1f8cdf3239 目录里面

v2.1.1.1  CRITICAL 01-10 10:16:48 │ [WinError 10054] 远程主机强迫关闭了一个现有的连接。

**联系方式**
- QQ号: 1413723178

**Comment by KilluaaaCHEN** [comment]
网络问题 检查代理或防火墙
