### ISSUE TITLE
将baas文件夹删除后无法重新安装，启动baaswindow提示发生异常

### ISSUE THREAD

**Issue by hanyuuK** [baas-pro/baas#42]
**电脑系统信息**
- 系统类型：[Windows / macOS]
- 苹果电脑芯片型号：[例如 Intel, M1, M2]

**Baas版本**
- Baas 版本号：[v2.1.1]

**模拟器信息**
- 模拟器类型：[Mumu12]
- 模拟器版本号：[例如 12]

**游戏区服**
- 游戏区服：[国服官包]

**问题描述**
- 功能模块：[下载]
- 详细问题描述：删除文件夹后无法重新下载，具体表现为管理员启动baaswindows时提示：
- 发生异常: Command '['git', 'clone', 'https://gitee.com/baas-pro/baas-win.git', 'baas']' returned non-zero exit status 128.

**运行截图/动图或视频**
![79cc5ed4a04c2712a2d35c2fb4581fd8](https://github.com/baas-pro/baas/assets/156170665/eaaea792-3c81-480e-b68d-079e00a320ea)

**运行日志**
- 请附上位于 `runtime/logs` 目录下的运行日志文件，以便我们分析问题。

**联系方式**
- QQ号:

**Comment by KilluaaaCHEN** [comment]
网络问题，检查代理或防火墙
