### ISSUE TITLE
源代码中的requirements.txt文件内有相冲突依赖

### ISSUE THREAD

**Issue by Georgebillion** [baas-pro/baas#44]
**电脑系统信息**
- 系统类型：Windows 10

**Baas版本**
- Baas 版本号：直接使用git clone下载的代码

**模拟器信息**
- 模拟器类型：MUMU12
- 模拟器版本号：12

**游戏区服**
- 游戏区服： 国服B包

**问题描述**
- 功能模块：pip依赖文件问题
- 详细问题描述：在requirement.txt文件内发现冲突依赖

**运行截图/动图或视频**
![image](https://github.com/baas-pro/baas/assets/40432824/4fbfa128-267a-41e4-8e1e-37193541198a)

**联系方式**
- QQ号: 402520246

**Comment by KilluaaaCHEN** [comment]
使用 4.9.0.80 即可
