### ISSUE TITLE
首次登录时，如果有买月卡，会在这里

### ISSUE THREAD

**Issue by a16797** [baas-pro/baas#46]
![MuMu12-20240121-111939](https://github.com/baas-pro/baas/assets/16302217/7f7b185b-ba2e-4db3-98cc-05ca933724ef)
![image](https://github.com/baas-pro/baas/assets/16302217/c3c6a152-a261-4a7f-9785-d5afd685d2e5)

**Comment by KilluaaaCHEN** [comment]
每天首次登录都必卡吗?
