### ISSUE TITLE
咖啡厅摸头国服更新后变得有延迟了，就是默认摸五次头但总是要漏几个没摸上

### ISSUE THREAD

**Issue by Gnarrrrr** [baas-pro/baas#51]
**电脑系统信息**
- 系统类型：[Windows 

**Baas版本**
- Baas 版本号：[最新]

**模拟器信息**
- 模拟器类型：[例如 Mumu12]
- 模拟器版本号：[例如 12]

**游戏区服**
- 游戏区服：[例如 国服b服]

**问题描述**
- 功能模块：[例如咖啡厅]
- 详细问题描述：[请尽可能详细描述遇到的问题]

**运行截图/动图或视频**
- 如果可能，请附加运行时的截图、GIF 或视频以帮助说明您遇到的问题

**运行日志**
- 请附上位于 `runtime/logs` 目录下的运行日志文件，以便我们分析问题。

**联系方式**
- QQ号: 

**其他补充信息**
- 在这里添加任何其他上下文信息。

**Comment by KilluaaaCHEN** [comment]
咖啡厅可以稍微整理干净点,会增加识别成功率
