### ISSUE TITLE
买体力卡了

### ISSUE THREAD

**Issue by a16797** [baas-pro/baas#53]
![image](https://github.com/baas-pro/baas/assets/16302217/73162f24-2283-4c28-adba-434e94175998)
![MuMu12-20240123-212919](https://github.com/baas-pro/baas/assets/16302217/07e9d0e2-2098-41c1-b22a-0d4715aa0bcd)
![image](https://github.com/baas-pro/baas/assets/16302217/c84e2cdb-9967-42a0-8af9-fa73958d7c16)
![image](https://github.com/baas-pro/baas/assets/16302217/86a0bf10-2e96-401c-94c9-a31af06721c1)

**Comment by a16797** [comment]
![image](https://github.com/baas-pro/baas/assets/16302217/d415d7fe-d9f2-48ca-be95-08f4b070c267)

**Comment by KilluaaaCHEN** [comment]
游戏没有执行反和谐，先执行一下
