### ISSUE TITLE
日服卡在主页检测了

### ISSUE THREAD

**Issue by Huisei1** [baas-pro/baas#54]
日服的主页UI变动了，点击的位置点不到右上角的菜单
v2.2.3  INFO     01-25 11:38:29 │ 开始第 4 次图片检索 end:home_student
v2.2.3  INFO     01-25 11:38:30 │ compare_image home_student SSIM:0.11 Result:False
v2.2.3  INFO     01-25 11:38:30 │ compare_image home_news-intl SSIM:0.07 Result:False
v2.2.3  INFO     01-25 11:38:30 │ compare_image home_store-error SSIM:0.03 Result:False
v2.2.3  INFO     01-25 11:38:30 │ click (1233,11)
Home键点击完返回主界面后，进行是否为主界面检测时，点的位置太靠上，没点到右上角的菜单导致检测一直失败

**Comment by weishao-sec** [comment]
我所有服都这样，用不了

**Comment by weishao-sec** [comment]
@KilluaaaCHEN 没解决

**Comment by KilluaaaCHEN** [comment]
更新到v2.2.4,还有问题q群找我
