### ISSUE TITLE
程序在推主线时，点击的关卡位置存在问题。

### ISSUE THREAD

**Issue by LINK-URIBOH** [baas-pro/baas#55]
**电脑系统信息**
- 系统类型：Windows

**Baas版本**
- Baas 版本号：2.2.0
**模拟器信息**
- 模拟器类型：Mumu
- 模拟器版本号：12

**游戏区服**
- 游戏区服：日服

**问题描述**
- 功能模块：推主线
- 详细问题描述：程序在尝试推主线时，点击的关卡位置存在问题。无法正确点击到下一关，而是一直在点击尚未解锁的关卡。
**运行截图/动图或视频**
![image](https://github.com/baas-pro/baas/assets/34745010/e7bb4000-a102-403c-8e97-cd82c7c9eacc)

**运行日志**
[log.txt](https://github.com/baas-pro/baas/files/14064350/log.txt)

**联系方式**
- QQ号: 1561057334

**Comment by IrPmine** [comment]
cy

**Comment by 4aware** [comment]
同样的问题

**Comment by Huberrian-Lei** [comment]
碰到同样的问题了，希望能快些解决

**Comment by AzeniaX** [comment]
same issue

**Comment by KilluaaaCHEN** [comment]
fixed
