### ISSUE TITLE
大概是登录那个弹框吧，这个问题也经常出现

### ISSUE THREAD

**Issue by a16797** [baas-pro/baas#57]
![MuMu12-20240127-211938](https://github.com/baas-pro/baas/assets/16302217/e5ed6d18-a054-48c2-a20d-e0524e369e00)
建议登录时勾选【今天不再显示】
![MuMu12-20240130-124815](https://github.com/baas-pro/baas/assets/16302217/f1f90bf7-13cf-4358-a799-b0d9c2896239)

**Comment by KilluaaaCHEN** [comment]
游戏bug卡公告图片了，只能等悠星研发解决。。。

**Comment by a16797** [comment]
> 游戏bug卡公告图片了，只能等悠星研发解决。。。

![image](https://github.com/baas-pro/baas/assets/16302217/f35ac719-cd8b-43bb-a346-7816cccfe391)
当天第一次登录时，勾选这个有没有可能会好一点
