### ISSUE TITLE
WebUI 输出 Log 致使浏览器占用大幅上升 / 支持清空 Log

### ISSUE THREAD

**Issue by w568w** [baas-pro/baas#59]
**电脑系统信息**
- 系统类型：ArchLinux

**Baas版本**
- Baas 版本号：v2.2.4

**模拟器信息**
- 模拟器类型：Waydroid
- 模拟器版本号：Latest

**游戏区服**
- 游戏区服：国服官包

**问题描述**
- 功能模块：网页前端
- 详细问题描述：在进行大量任务时（例如完成 80 个学生的 Momotalk），有时会输出大量日志（非死循环），而随着网页前端因此而变卡，其所在浏览器的内存占用也会以极快的速度上升，峰值可以达到 7~8 GB，直至整个浏览器卡死。应当有选项允许清空较旧的日志或限制最大日志的长度。

**运行截图/动图或视频**
![图片](https://github.com/baas-pro/baas/assets/8389787/28e2b044-072e-44b2-975e-d5fb695c8ec9)

**运行日志**
和运行日志内容无关。日志均为正常输出，调试输出已关闭。

**联系方式**
- QQ号: N/A

**其它信息**
- 浏览器：LibreWolf 122.0-1
- 系统信息：

```
操作系统： Arch Linux 
KDE Plasma 版本： 5.27.10
KDE 程序框架版本： 5.114.0
Qt 版本： 5.15.12
内核版本： 6.6.14-x64v2-xanmod1-1 (64 位)
图形平台： Wayland
处理器： 16 × AMD Ryzen 7 4800H with Radeon Graphics
内存： 15.0 GiB 内存
图形处理器： AMD Radeon Graphics
制造商： LENOVO
```

**Comment by KilluaaaCHEN** [comment]
浏览器可以关掉，不用一直开着~ 下个版本优化下日志
