### ISSUE TITLE
有关于。日服碧蓝档案日程进行的时候，卡识别问题

### ISSUE THREAD

**Issue by 123xuanhua** [baas-pro/baas#61]
**电脑系统信息**
惠普光影精灵8
- 系统类型：[Windows / macOS]
- win
- 苹果电脑芯片型号：[例如 Intel, M1, M2]

**Baas版本**
2.3.0
- Baas 版本号：[例如 v2.0.5]

**模拟器信息**
- 模拟器类型：[例如 Mumu12, 雷电, 夜神 ...]mumu
- 模拟器版本号：[例如 12]12

**游戏区服**
- 游戏区服：日服[例如 国服官包 国服B包 日服 国际服]

**问题描述**
- 功能模块：日程[例如 普通开图 咖啡厅 日程 ...]
- 详细问题描述：[请尽可能详细描述遇到的问题]
日程不是有六张票，就在六张票用完的时候，再点一下查看学生。它就会显示购买票的界面，然后就会卡识别。
**运行截图/动图或视频**
![image](https://github.com/baas-pro/baas/assets/155611251/75525965-b3a1-4ad4-8cd4-e81fbd88327e)
- 如果可能，请附加运行时的截图、GIF 或视频以帮助说明您遇到的问题

**运行日志**
- 请附上位于 `runtime/logs` 目录下的运行日志文件，以便我们分析问题。

**联系方式**
- QQ号: 2630172946

**其他补充信息**
- 在这里添加任何其他上下文信息。

**Comment by KilluaaaCHEN** [comment]
fixed
