### ISSUE TITLE
困难模式下拾取青辉石会卡脚本

### ISSUE THREAD

**Issue by MCOTF** [baas-pro/baas#63]
**电脑系统信息**
- 系统类型：Windows
- 苹果电脑芯片型号：r7 5800u

**Baas版本**
- Baas 版本号：2.2.4

**模拟器信息**
- 模拟器类型：Mumu12

**游戏区服**
- 游戏区服：国服官包

**问题描述**
- 功能模块：困难开图
- 详细问题描述：困难模式下拾取青辉石会卡脚本

**运行截图/动图或视频**
- 
![image](https://github.com/baas-pro/baas/assets/97014724/876dbfbf-9af4-41d4-9b94-0d1fcec6a076)
![image](https://github.com/baas-pro/baas/assets/97014724/128e62aa-17f5-4bff-8563-148c0e7954e1)

**运行日志**
- 请附上位于 `runtime/logs` 目录下的运行日志文件，以便我们分析问题。
[2024-02-05_baas.txt](https://github.com/baas-pro/baas/files/14162893/2024-02-05_baas.txt)

**联系方式**
- QQ号: 2549254469

**其他补充信息**
- 在这里添加任何其他上下文信息。

**Comment by KilluaaaCHEN** [comment]
这是哪一个关卡

**Comment by MCOTF** [comment]
@KilluaaaCHEN 早忘了，不是在9就是在9附近

**Comment by KilluaaaCHEN** [comment]
fixed
