### ISSUE TITLE
MomoTalk BUG

### ISSUE THREAD

**Issue by jjssk** [baas-pro/baas#64]
**电脑系统信息**华硕天选4
- 系统类型：[Windows ]
- 苹果电脑芯片型号：[Intel]

**Baas版本**
- Baas 版本号：[ v2.3.0]

**模拟器信息**
- 模拟器类型：[Mumu12]
- 模拟器版本号：[例如 3.8.1.2675]

**游戏区服**
- 游戏区服：[国服B包]

**问题描述**
- 功能模块：[momotalk]
- 详细问题描述：[回消息的框不完全出现在momotalk里,点击时会点击两次进入商店,有时会只点击一次后卡在主界面]

**运行截图/动图或视频**
- 如果可能，请附加运行时的

https://github.com/baas-pro/baas/assets/156515091/6f9fdc94-f7d0-4d91-a147-d42f0fb02885

截图、GIF 或视频以帮助说明您遇到的问题

**运行日志**
[2024-02-15_baas - 副本.txt](https://github.com/baas-pro/baas/files/14292197/2024-02-15_baas.-.txt)

- 请附上位于 `runtime/logs` 目录下的运行日志文件，以便我们分析问题。

**联系方式**
- QQ号:3177486518 

**其他补充信息**
- 在这里添加任何其他上下文信息。

**Comment by KilluaaaCHEN** [comment]
fixed
