### ISSUE TITLE
战术对抗赛：希望能设置X次数对战，在指定对战X次后，领取战术对抗赛的每日奖励

### ISSUE THREAD

**Issue by HDZM** [baas-pro/baas#65]
**电脑系统信息**
- 系统类型：Windows 
- 苹果电脑芯片型号：intel
**Baas版本**
- Baas 版本号：v2.3.0

**模拟器信息**
- 模拟器类型： Mumu12
- 模拟器版本号：

**游戏区服**
- 游戏区服：国际服

**问题描述**
- 功能模块：战术对抗赛
- 详细问题描述：希望能设置X次数对战，在指定对战X次后，领取战术对抗赛的每日奖励

**运行截图/动图或视频**
- 如果可能，请附加运行时的截图、GIF 或视频以帮助说明您遇到的问题

**运行日志**
- 请附上位于 `runtime/logs` 目录下的运行日志文件，以便我们分析问题。

**联系方式**
- QQ号: 472176618

**其他补充信息**
- 在这里添加任何其他上下文信息。

**Comment by KilluaaaCHEN** [comment]
fixed
