### ISSUE TITLE
希望允许BAAS扫荡时选择一键MAX或者在指名手配和学院交流会中选择大于9的选项

### ISSUE THREAD

**Issue by HS7097** [baas-pro/baas#66]
**电脑系统信息**
- 系统类型：[Windows]

**Baas版本**
- Baas 版本号：[v2.3.0]

**游戏区服**
- 游戏区服：[日服]

**问题描述**
- 功能模块：[指名手配，普通困难，学院交流会，活动]
- 详细问题描述：[希望允许BAAS扫荡时选择一键MAX或者在指名手配和学院交流会中选择大于9的选项]

**其他补充信息**
- 在这里添加任何其他上下文信息。
- 
![image](https://github.com/baas-pro/baas/assets/103177863/5803dc3f-1dcb-4d91-826f-d71a261caedd)

**Comment by KilluaaaCHEN** [comment]
普通关卡&学院交流会  填99，特殊委托填9会直接点击max
