### ISSUE TITLE
希望n图扫荡功能添加【根据现有碎片最少者的选择效率最优图刷取】功能

### ISSUE THREAD

**Issue by dhujsi** [baas-pro/baas#67]
**其他补充信息**
- 目前遇到n2 n3的操作是装备-保有数升序-选取关卡。如果能集成到baas里就好了。一般来说碎片也很少有归零的时候，多少会带点尾数。就算偶尔归零，也会随着掉落副产物回到碎片最少的情况

**Comment by KilluaaaCHEN** [comment]
怎么判断你要需要T几的装备呀，目前只能指定具体关卡
