### ISSUE TITLE
能不能增加勾选公告的【今日不再显示】

### ISSUE THREAD

**Issue by a16797** [baas-pro/baas#68]
**电脑系统信息**
- 系统类型：[Windows / ]
**Baas版本**
- Baas 版本号：最新

**模拟器信息**
- 模拟器类型：[例如 Mumu12, ..]
- 模拟器版本号：[例如 12]

**游戏区服**
- 游戏区服：[例如 国服官包 
- 
**问题描述**
- 功能模块：卡公告图片
- 详细问题描述：
- 
![image](https://github.com/baas-pro/baas/assets/16302217/b9973de1-db5b-4b18-925a-5af96a3545e5)

能不能每天首次登录时，把这个勾上。应该就不会卡了
![image](https://github.com/baas-pro/baas/assets/16302217/7d31b72b-2a3f-43f8-a959-14b6adcb31fb)

**Comment by KilluaaaCHEN** [comment]
这玩意儿是游戏bug，她们修复之后就好了
