### ISSUE TITLE
日服剧情点击BUG，第一次剧情结束后会在剧情选择页无限点击未解锁章节

### ISSUE THREAD

**Issue by Huberrian-Lei** [baas-pro/baas#69]
**电脑系统信息**
- 系统类型：Windows 

**Baas版本**
- Baas 版本号：2.4.0

**模拟器信息**
- 模拟器类型：[蓝叠]
- 模拟器版本号：[例如 12]

**游戏区服**
- 游戏区服：日服

**问题描述**
- 功能模块：主线剧情
- 详细问题描述：主线剧情进入后，第一次可正常结束，第一次剧情结束后，会在剧情选择界面无限点击未解锁剧情，希望能尽快修复。

**运行截图/动图或视频**
![5b504314a3dedcc97c2c8e0b51788f1a](https://github.com/baas-pro/baas/assets/125622038/8ed18f70-797d-483e-beb2-fd9d4419ef68)

**运行日志**
- 请附上位于 `runtime/logs` 目录下的运行日志文件，以便我们分析问题。

**联系方式**
- QQ号: 2723425991

**其他补充信息**
- 在这里添加任何其他上下文信息。

**Comment by Huberrian-Lei** [comment]
[运行日志.txt](https://github.com/baas-pro/baas/files/14396630/default.txt)

**Comment by KilluaaaCHEN** [comment]
重复bug #55
