### ISSUE TITLE
主线剧情自动化卡死

### ISSUE THREAD

**Issue by RealStarVon** [baas-pro/baas#71]
**电脑系统信息**
- 系统类型：Windows
- 
**Baas版本**
- Baas 版本号：[例如 v2.0.5]4群里下的，大概是最新版（发布日期2024.3.2）

**模拟器信息**
- 模拟器类型：mumu12
- 模拟器版本号：12

**游戏区服**
- 游戏区服：日服
**问题描述**
- 功能模块：主线剧情
- 详细问题描述：通过了第十关，解锁了十一关但baas始终在点十二关导致卡住的现象

**运行日志**
- 请附上位于 `runtime/logs` 目录下的运行日志文件，以便我们分析问题。

**联系方式**
- QQ号: 

**其他补充信息**
- 在这里添加任何其他上下文信息。

请求：由于日服有连续看剧情的功能，是否可以利用这个功能做独立适配？非常感谢！

**Comment by MeteorSword** [comment]
尝试进行了复现，在从头开始一章的剧情时和中途开始时均会出现此情况

**Comment by KilluaaaCHEN** [comment]
重复bug #55
