### ISSUE TITLE
日服主线故事无法进行

### ISSUE THREAD

**Issue by null1213** [baas-pro/baas#73]
**电脑系统信息**
- 系统类型：windows

**Baas版本**
- Baas 版本号：[ v2.4.0]

**模拟器信息**
- 模拟器类型：[蓝叠5.]

**游戏区服**
- 游戏区服：[日服]

**问题描述**
- 功能模块：[主线故事.]
- 详细问题描述：[进主线看完一话后，会点错地方，然后卡死]

**运行日志**
- 请附上位于 `runtime/logs` 目录下的运行日志文件，以便我们分析问题。

**联系方式**
- QQ号: 1260452768

**Comment by KilluaaaCHEN** [comment]
重复bug #55
