### ISSUE TITLE
BAAS界面-日程BUG

### ISSUE THREAD

**Issue by ice-forever** [baas-pro/baas#74]
**电脑系统信息**
- 系统类型：Windows

**Baas版本**
- Baas 版本号：2.4.2

**模拟器信息**
- 模拟器类型：Mumu12
- 模拟器版本号：12

**游戏区服**
- 游戏区服：国服官包

**问题描述**
- 功能模块：日程
- 详细问题描述：开始执行日程后，BAAS出现问题停止。另外，日程序号需要应该为1-8或者1-7

**运行截图/动图或视频**
- ![image](https://github.com/baas-pro/baas/assets/74451255/10abf670-1821-4241-b117-7fa47f25fad6)
-  配置如下
![image](https://github.com/baas-pro/baas/assets/74451255/cae12b3b-bb7b-435b-a3c6-584f8708b768)

**运行日志**
[2024-03-21_baas.zip](https://github.com/baas-pro/baas/files/14691687/2024-03-21_baas.zip)因html无法上传上传了zip格式

**Comment by KilluaaaCHEN** [comment]
fixed
