### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by lucky233duck** [baas-pro/baas#75]
**电脑系统信息**
- 系统类型：win11

**Baas版本**
- Baas 版本号：v2.0.5
**模拟器信息**
- 模拟器类型：Mumu12
- 模拟器版本号：12

**游戏区服**
- 游戏区服：国服B包

**问题描述**
- win11如果游戏画面不对电脑会变得非常卡，但在win10电脑上没这个问题，可能是一直在疯狂截图导致的？
**运行截图/动图或视频**
- 如果可能，请附加运行时的截图、GIF 或视频以帮助说明您遇到的问题

https://github.com/baas-pro/baas/assets/90335748/5b65f5b3-6fee-4858-90c0-36570e47c1cf

**运行日志**
- 请附上位于 `runtime/logs` 目录下的运行日志文件，以便我们分析问题。

**联系方式**
- QQ号: 2774005606

**其他补充信息**
- 在这里添加任何其他上下文信息。

**Comment by KilluaaaCHEN** [comment]
脚本会吃cpu，脚本跑不起来，看看配置够不够
