### ISSUE TITLE
日程无法正常使用

### ISSUE THREAD

**Issue by GenLiya** [baas-pro/baas#77]
**电脑系统信息**
- 系统类型：Windows 

**Baas版本**
- Baas 版本号： v2.4.2

**模拟器信息**
- 模拟器类型：Mumu12
- 模拟器版本号：[例如 12]

**游戏区服**
- 游戏区服：国服官包 

**问题描述**
- 功能模块：日程 
- [详细问题描述：崔尼蒂，和红冬的日程不识别](url)

**运行截图/动图或视频**

https://github.com/baas-pro/baas/assets/139315357/8f2b0803-b22f-4185-bfab-32c51f6a6bec

- 如果可能，请附加运行时的截图、GIF 或视频以帮助说明您遇到的问题

**运行日志**
v2.4.2  INFO     03-30 14:20:41 │ 开始第 3 次图片检索 end:schedule_menu

v2.4.2  INFO     03-30 14:20:41 │ compare_image schedule_menu SSIM:1.00 Result:True

v2.4.2  INFO     03-30 14:20:41 │ compare_image schedule_surplus SSIM:-0.13 Result:False

v2.4.2  INFO     03-30 14:20:41 │ compare_image schedule_surplus2 SSIM:0.24 Result:False

v2.4.2  INFO     03-30 14:20:41 │ swipe 911 199 911 600 duration:0.1

v2.4.2  INFO     03-30 14:20:42 │ swipe 911 199 911 600 duration:0.1

v2.4.2  INFO     03-30 14:20:43 │ swipe 911 650 911 40 duration:0.55

v2.4.2  CRITICAL 03-30 14:20:45 │ Exception occurred: 7

v2.4.2  CRITICAL 03-30 14:20:45 │ Stack trace:
Traceback (most recent call last):
File "common\process.py", line 12, in baas_dashboard
File "common\baas.py", line 225, in dashboard
File "modules\daily\schedule.py", line 46, in start
File "modules\daily\schedule.py", line 54, in choose_course
File "modules\daily\schedule.py", line 68, in to_college
File "modules\daily\schedule.py", line 73, in to_course_info
KeyError: 7

**联系方式**
- QQ号: 2533764098

**其他补充信息**
- 在这里添加任何其他上下文信息。

**Comment by KilluaaaCHEN** [comment]
更新到2.5.0
