### ISSUE TITLE
baas日程识别问题

### ISSUE THREAD

**Issue by Mosiinn** [baas-pro/baas#79]
**电脑系统信息**
- 系统类型：[Windows]
- 电脑芯片型号：[Intel]

**Baas版本**
- Baas 版本号：[例如 v2.5.0]

**模拟器信息**
- 模拟器类型：[雷电]
- 模拟器版本号：[安卓9.0]

**游戏区服**
- 游戏区服：[国际服 日服]

**问题描述**
- 功能模块：[日程
- 详细问题描述：[运行日程是偶尔会卡识别。无法识别到山海经区，baas内选择du会点击山海经区，选择百鬼会点击du区。无法按照设定好的次数完成点击，七张票只能完成六次点击。]

**运行截图/动图或视频**
- 如果可能，请附加运行时的截图、GIF 或视频以帮助说明您遇到的问题
- 卡识别情况如下
![QQ图片20240403141203](https://github.com/baas-pro/baas/assets/165876479/8b1f41c8-f2c5-46a3-9d06-b94e94581e2f)
![QQ图片20240403141208](https://github.com/baas-pro/baas/assets/165876479/aeeb61f5-8ee1-49a0-ad2a-d1161bd77c6a)
![QQ图片20240403141211](https://github.com/baas-pro/baas/assets/165876479/515611a0-e999-461d-8599-1fce034d064b)
- 无法完成点击情况如下
![QQ截图20240403141339](https://github.com/baas-pro/baas/assets/165876479/a8c8aa64-71da-4eac-ab3c-978cb1d64cdb)
![QQ截图20240403141348](https://github.com/baas-pro/baas/assets/165876479/40e4ee8f-f0db-45b6-9578-0c08085c7cd2)

**运行日志**
- 请附上位于 `runtime/logs` 目录下的运行日志文件，以便我们分析问题。

**联系方式**
- QQ号: 1870462891

**其他补充信息**
- 在这里添加任何其他上下文信息。

**Comment by KilluaaaCHEN** [comment]
更新到v2.5.0.3
