### ISSUE TITLE
国服困难开图15-3出现问题

### ISSUE THREAD

**Issue by ice-forever** [baas-pro/baas#80]
**电脑系统信息**
- 系统类型：Windows

**Baas版本**
- Baas 版本号：v2.5.0.2

**模拟器信息**
- 模拟器类型：Mumu12

**游戏区服**
- 游戏区服：国服官包

**问题描述**
- 功能模块：困难开图
- 详细问题描述：15-3困难开图仅通关设置出现问题，15-3未开图但是程序识别为没有需要开图的关卡

**运行截图/动图或视频**
![image](https://github.com/baas-pro/baas/assets/74451255/80f0b6fc-bf02-4ec7-aabc-75f85ad76cac)
![image](https://github.com/baas-pro/baas/assets/74451255/eb26237d-7e3a-435e-b65d-344e2b6022b1)

**运行日志**
- 请附上位
[2024-04-08_baas.zip](https://github.com/baas-pro/baas/files/14901034/2024-04-08_baas.zip)

**Comment by KilluaaaCHEN** [comment]
fixed
