### ISSUE TITLE
国际服特殊任务扫荡最后一关报错

### ISSUE THREAD

**Issue by nevein11** [baas-pro/baas#84]
v3.1.9  INFO     04-25 09:29:43 │ 开始第 7 次图片检索 end:special_entrust_menu
v3.1.9  INFO     04-25 09:29:43 │ Now Loading 0 seconds...
v3.1.9  INFO     04-25 09:29:43 │ Now Loading 0 seconds...
v3.1.9  INFO     04-25 09:29:44 │ Now Loading 1 seconds...
v3.1.9  INFO     04-25 09:29:45 │ compare_image special_entrust_menu SSIM:1.00 Result:True
v3.1.9  INFO     04-25 09:29:45 │ click (950,200)
v3.1.9  INFO     04-25 09:29:46 │ compare_image wanted_stage-list SSIM:0.23 Result:False
v3.1.9  INFO     04-25 09:29:46 │ compare_image wanted_stage-list SSIM:0.20 Result:False
v3.1.9  INFO     04-25 09:29:47 │ compare_image wanted_stage-list SSIM:1.00 Result:True
v3.1.9  INFO     04-25 09:29:47 │ swipe 911 199 911 600 duration:0.1
v3.1.9  INFO     04-25 09:29:47 │ swipe 911 199 911 600 duration:0.1
v3.1.9  INFO     04-25 09:29:48 │ swipe 911 650 911 40 duration:0.55
v3.1.9  INFO     04-25 09:29:50 │ swipe 911 650 911 40 duration:0.55
v3.1.9  CRITICAL 04-25 09:29:53 │ Exception occurred: 13
v3.1.9  CRITICAL 04-25 09:29:53 │ Stack trace:
Traceback (most recent call last):
  File "common\process.py", line 12, in baas_dashboard
  File "common\baas.py", line 284, in dashboard
  File "modules\attack\special_entrust.py", line 68, in start
  File "modules\attack\special_entrust.py", line 87, in choose_entrust
  File "modules\attack\special_entrust.py", line 99, in get_lv_position
KeyError: 13

选择关卡13时会提示以上错误，并停止运行。

**Comment by KilluaaaCHEN** [comment]
已修复更新至3.2.0
