### ISSUE TITLE
偶尔会点击不了，手动重启atx之后就正常了

### ISSUE THREAD

**Issue by a16797** [baas-pro/baas#85]
win10，mumu12最新版
![image](https://github.com/baas-pro/baas/assets/16302217/d273291c-e608-41b4-a7f1-763fc1ae193a)

[2024-04-25_baas.zip](https://github.com/baas-pro/baas/files/15110952/2024-04-25_baas.zip)

**Comment by KilluaaaCHEN** [comment]
模拟器是不是开了很久没有关过

**Comment by a16797** [comment]
也没很久吧  开一天就会这样

**Comment by KilluaaaCHEN** [comment]
fixed
