### ISSUE TITLE
卡登陆公告

### ISSUE THREAD

**Issue by a16797** [baas-pro/baas#86]
前一天启动，一直没关脚本，第二天会卡登陆公告。忘记截图了，现在没图片，明天看看能不能补。
大概是下图这样，中间是公告
![image](https://github.com/baas-pro/baas/assets/16302217/e5da6b13-7912-4c7c-b76e-c2a09aef0aa0)

[2024-04-24_baas.zip](https://github.com/baas-pro/baas/files/15111106/2024-04-24_baas.zip)

**Comment by a16797** [comment]
![image](https://github.com/baas-pro/baas/assets/16302217/754a2fd7-168a-4d0f-8424-d03b188184d8)
![MuMu12-20240427-195139](https://github.com/baas-pro/baas/assets/16302217/fc10e419-d093-4ff8-ac40-e8357b4a9ad7)
[2024-04-27_baas - 副本.zip](https://github.com/baas-pro/baas/files/15138096/2024-04-27_baas.-.zip)

**Comment by KilluaaaCHEN** [comment]
模拟器一直没关过吗

**Comment by KilluaaaCHEN** [comment]
fixed
