### ISSUE TITLE
希望国际服-活动 某科学的青春记录 增加非后4关扫荡 

### ISSUE THREAD

**Issue by anlo1220** [baas-pro/baas#87]
希望国际服-活动 某科学的青春记录 增加非后4关扫荡 
新手还没80等 打不到3星
![image](https://github.com/baas-pro/baas/assets/61088753/c4835595-ce26-4b0c-975f-3510eed41458)

**Comment by KilluaaaCHEN** [comment]
加上了

**Comment by anlo1220** [comment]
感谢
