### ISSUE TITLE
关于  扫荡困难关卡 出现BUG

### ISSUE THREAD

**Issue by Violet816Q** [baas-pro/baas#88]
在使用的过程发现，设置3次扫荡，但是bass前两次都没点上，只有最后一下才点上了`
最开始以为是偶然，后面几天都是这样de

（模拟器mumu，分辨率也符合条件）

辛苦up努力持续更新BASS

**Comment by KilluaaaCHEN** [comment]
用最新版本试试呢3.2.3.2

**Comment by KilluaaaCHEN** [comment]
fixed
