### ISSUE TITLE
国际服-活动 某科学的青春记录 赠品交换所 按下更新后会直接停止

### ISSUE THREAD

**Issue by anlo1220** [baas-pro/baas#89]
国际服-活动 某科学的青春记录 赠品交换所 按下更新后会直接停止
![image](https://github.com/baas-pro/baas/assets/61088753/bf800fbf-9047-48c5-8669-f847a680d6b2)
![image](https://github.com/baas-pro/baas/assets/61088753/dc9cbc9d-3149-4e04-81c3-e76148927335)

**Comment by KilluaaaCHEN** [comment]
已修复,请更新至3.2.3.2
