### ISSUE TITLE
日程和商店购买清空原有内容后无法添加

### ISSUE THREAD

**Issue by Zenchar** [baas-pro/baas#9]
日程和商店购买清空原有内容后切到其他栏目后切回来，会导致添加按钮无法显示
![动画1](https://github.com/baas-pro/baas/assets/80956273/a1f1a3ec-b55a-46df-9e38-4da766950262)

**Comment by KilluaaaCHEN** [comment]
这种bug都被你找到了，哈哈 👍🏻

**Comment by KilluaaaCHEN** [comment]
fixed
