### ISSUE TITLE
自动开图有时不能正确切换章节

### ISSUE THREAD

**Issue by rainRb** [baas-pro/baas#91]
当我设置刷取10 11 12章困难关卡时，，此时进度10-1，刷完10-3之后就卡住了。
无论是国服还是国际服，普通关还是困难关，每个章节的最后一关刷完之后都会卡住。但是如果设置刷取10 11 12章困难关卡，且此时10-3已经刷完了，就可以正确进入11-1

**Comment by rainRb** [comment]
![image](https://github.com/baas-pro/baas/assets/97787236/e65d318f-8acd-4110-852c-ca1cb116974f)
我的设置如图

**Comment by rainRb** [comment]
看了一下他识别出来了11-4-box？反正到这之后就一直卡图片检测了
![image](https://github.com/baas-pro/baas/assets/97787236/14eb64a9-b8b4-4dc3-87f0-b1974499a197)


![image](https://github.com/baas-pro/baas/assets/97787236/611c1a27-7955-4724-bfc2-57d63045d6e2)



https://github.com/baas-pro/baas/assets/97787236/3b89431e-db2a-4d08-8cd8-ded90fa00f98

[这个是日志文件，GitHub不能上传html所以我改成了txt2024-05-19_baas3.txt](https://github.com/baas-pro/baas/files/15368224/GitHub.html.txt2024-05-19_baas3.txt)

**Comment by KilluaaaCHEN** [comment]
fixed
