### ISSUE TITLE
游戏启动转圈圈界面卡死，baas似乎无法主动重启游戏，只会一直卡在该界面

### ISSUE THREAD

**Issue by melon0918** [baas-pro/baas#96]
![EBYYLK5W}(@6RU6WWB8V~GY](https://github.com/baas-pro/baas/assets/77735556/df847d6f-345d-48cf-b926-7f2b38869e9f)
![C0GPQ)YV~@JLZZT_TD(_$MQ](https://github.com/baas-pro/baas/assets/77735556/16cc93b8-24da-427a-b889-6f77de7e2111)
如图，即使自动重启ATX，游戏也依旧卡在该界面，无法自动重启游戏

**Comment by KilluaaaCHEN** [comment]
这是梯子问题，开梯子了吗，建议使用mumu使用官方自带加速器

**Comment by melon0918** [comment]
> 这是梯子问题，开梯子了吗，建议使用mumu使用官方自带加速器

是梯子的锅，不过梯子会自动切可用节点，所以遇上后重启游戏就好了。
